### ISSUE TITLE
run.py way to concret

### ISSUE THREAD

**Issue by broeder-j** [marvel-nccr/quantum-eden#38]
run.py a nice, but naive try to implement a one command run the same with different codes. But you fix/assume a workflow interface (first of what inputs are required, second what their name/label is). Which was never agreed on and should not be done/will not work. I will not change ANY interfaces anymore. Instead all command line input should be parsed to individual run_codename routines that can do what every they want with the cmd input.

**Comment by ltalirz** [comment]
Dear Jens, please excuse my naivity - I am not a workflow expert and I am totally open for pull requests that change the behavior of run.py :-)
Forwarding parsed parameters to a plugin-dependent run-function seems totally fine with me. 
We just need to define the parameters this routine should take (code, structure, kpoints, ...?).

I'm closing the issue here, please continue on https://github.com/aiidateam/aiida-max-examples/issues so that the discussion stays at the right place.
